services:
  - type: web
    name: mathmon
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir python --bind 0.0.0.0:$PORT server:app
    healthCheckPath: /api/health
    plan: free
